### ISSUE TITLE
set-env warnings

### ISSUE THREAD

**Issue by henryiii** [ilammy/msvc-dev-cmd#16]
The change here: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
causes a lot of warnings to be produced when using the action. I believe `@actions/core` needs to be 1.2.6 or higher.

Also, the `v1` tag has not been updated to the latest v1 series. The last few releases were not made "GitHub" releases either, so 1.3.0 still shows up in the side bar on the webpage.

**Comment by henryiii** [comment]
I think this already has been fixed on master, actually, I see a bump to 1.2.6 commit. Then can we get a new v1 release? I can move to `@master` :'( for now.

**Comment by ilammy** [comment]
I'm sorry, got tangled up :cry: I've updated the `v1` tag to point to the latest release which includes updates to `@actions/core`. Please check it out.

**Comment by kwhat** [comment]
Thanks for the fix, seems to be working :+1:

**Comment by henryiii** [comment]
Works for me too! Thanks!
