### ISSUE TITLE
set-env is deprecated and generates warnings

### ISSUE THREAD

**Issue by scatterflower** [ilammy/msvc-dev-cmd#17]
The action fills up the log with warnings about set-env being deprecated, and soon being disabled.

The warning provides this url for more information: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by henryiii** [comment]
Duplicate of #16, by the way. ;)

**Comment by henryiii** [comment]
By the way, looks like master may already have upgraded to actions/core 1.2.6, which should fix the problem.

**Comment by ilammy** [comment]
@scatterflower, thanks for a report!

As noted in #16, I've updated the `v1` tag to the version which should include fix for this issue. Please check it out.

**Comment by scatterflower** [comment]
ah, sorry about the duplicate. looks like i submitted the issue at nearly the exact same time, and didn't see that someone else posted it! strange coincidence indeed.
