### ISSUE TITLE
'Win32' as an alias of 'x86'

### ISSUE THREAD

**Issue by PazerOP** [ilammy/msvc-dev-cmd#26]
There are quite a few bits during the setup and management of windows projects where your two options for architectures are `Win32` and `x64` instead of the more logical `x86` and `x64`.

Is it possible that the `arch` parameter for this script could be made to also accept `Win32` as an alias of `x86` (and `Win64` as `x64` while we're at it)? This change would simplify some github actions scripts I have by a fair amount.

**Comment by ilammy** [comment]
The parameters are meant to mirror MSVC's batch script to be more familiar (and easier to implement), but I see no reason why they *must* be limited to the values supported by the MSVC's batch script.

If that makes your life easier, I'd add them. The architecture names are a clusterfuck anyway, I don't see how a couple more would make things worse.

**Comment by ilammy** [comment]
I've just published `v1.6.0` (aliased as `v1`) which should now accept `win32` and `win64` as aliases for `x86` and `x64` respectively. Matching is case-insensitive so `win32`, `Win32`, `WIN32` are all the same.

**Comment by ilammy** [comment]
Since this seems to be working and @PazerOP reacted with “👍”, I guess we're done here.
