### ISSUE TITLE
Add Usage example to README for other inputs..

### ISSUE THREAD

**Issue by slontis** [ilammy/msvc-dev-cmd#33]
It might be nice to show how to use some of the other inputs that you allow setting (for github action newbies).
I am adding msvc-dev-cmd to openssl.

**Comment by ilammy** [comment]
Nice idea, @slontis. Thanks!

I've updated README to include some examples of usage with inputs.

Turns out that existing examples was even slightly incorrect 🤦

**Comment by slontis** [comment]
Thanks..
