### ISSUE TITLE
Accept x86_64 as an alias to x64

### ISSUE THREAD

**Issue by aminya** [ilammy/msvc-dev-cmd#39]
D programming language uses x86_64 as the name of the x64 arch. Could you support accepting `x86_64` as the arch input?

**Comment by ilammy** [comment]
@aminya, I've just released `v1.9.0` (aliased as `v1`) which should accept `x86_64` as an alias for `x64`.

Sorry for closing the issue a bit early, before you verify. I'm using this repo as a guinea pig for GitHub features. Please reopen if `x86_64` does not work for you.

**Comment by pzhlkj6612** [comment]
guinea pig... haha

**Comment by aminya** [comment]
Thank you so much! I will verify this, and if there was an issue, I will make a pull request.
