### ISSUE TITLE
How to use latest XP toolset v141_xp?

### ISSUE THREAD

**Issue by askovpen** [ilammy/msvc-dev-cmd#65]
How to use latest XP toolset v141_xp?

**Comment by ilammy** [comment]
Which image are you using?

Looks like Windows XP support is pre-installed only in `windows-2019`, while for `windows-2022` (= `windows-latest`) you need to install the Visual Studio component manually, like here: https://github.com/actions/runner-images/issues/6067#issuecomment-1213069040

[The interwebs are also warning](https://learn.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-170) that you might need to get ahold of the old C++ runtime libs that still have Windows XP support.
