### ISSUE TITLE
PATH entries appended at the end, so default linker is not MSVC

### ISSUE THREAD

**Issue by SanderVocke** [ilammy/msvc-dev-cmd#85]
In my Actions run, Git has its mingw binaries folder in the path. It seems there is a link.exe there and this one is taking precedence over the PATH set by this Action.

Since we are talking about build tooling, wouldn't it be better to prepend the entries to the PATH instead of appending? That way we are sure after running this Action, that the MSVC tools get picked first.

**Comment by pzhlkj6612** [comment]
Hi.

> It seems there is a link.exe there and this one is taking precedence over the PATH set by this Action.

Interesting. No other users have reported this issue.

Can you please post the value of "PATH" before and after running this action? You can find it in your CI log.

**Comment by SanderVocke** [comment]
My bad, sorry for the confusion. It looks like I am simply affected by #25.
