### ISSUE TITLE
Windows, Error DCMAKE_*_FLAGS with bash

### ISSUE THREAD

**Issue by Veha0001** [ilammy/msvc-dev-cmd#86]
Command:
```bash
cmake -G Ninja -S .  -B build \
-DCMAKE_C_FLAGS="/MP"  \
-DCMAKE_CXX_FLAGS="/MP" \ 
.....
```
Error output: 
```bash
c1xx: fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory
    MP
    c1xx: fatal error C1083: Cannot open source file: 'Files/Git/MP': No such file or directory
    Generating Code...
    ninja: build stopped: subcommand failed.
```

**Comment by pzhlkj6612** [comment]
Hi! Please provide a minimal reproducible example about your workflow and CMakeLists.txt.

**Comment by Veha0001** [comment]
- [build.yml](https://github.com/Veha0001/aseprite/blob/main/.github/workflows/build.yml)

- [CMakeLists.txt](https://github.com/aseprite/aseprite/blob/main/CMakeLists.txt)

> Hi! Please provide a minimal reproducible example about your workflow and CMakeLists.txt.

**Comment by Veha0001** [comment]
I initially used shell: `bash`, which caused issues with `-DCMAKE_CXX_FLAGS="/MP"` and led to errors like:
```bash
c1xx: fatal error C1083: Cannot open source file: 'C:/Program': No such file or directory
```
Switching to shell: `cmd` fixed this, allowing the flag to work as expected. My GitHub Actions config now uses cmd:
```yml
- name: Generating Makefiles
  shell: cmd
  run: |
    mkdir build
    cmake -S . -B build -G Ninja ^
      -DCMAKE_CXX_FLAGS="/MP" ^
      -DCMAKE_C_FLAGS="/MP" ^
      -DENABLE_CCACHE=OFF ^
      -DOPENSSL_USE_STATIC_LIBS=TRUE ^
      -DCMAKE_BUILD_TYPE=${{ inputs.buildtype }} ^
      -DLAF_BACKEND=skia ^
      -DSKIA_DIR=skia ^
      -DSKIA_LIBRARY_DIR=skia/out/Release-x64 ^
      -DSKIA_LIBRARY=skia/out/Release-x64/skia.lib 
- name: Compiling
  shell: cmd
  run: |
    cd build && ninja
```

**Comment by pzhlkj6612** [comment]
> Switching to shell: `cmd` fixed this, allowing the flag to work as expected.

Good to hear that!



> I initially used shell: `bash`...

Did you try PowerShell? IIRC it's the default environment on Windows runners?
